# Github ACtions

name: End to End CI/CD workflow for Java Applicaton with Maven, Sonar and k8s Intergation

on:
  push:
    branches: 
      - main
#   pull_request:
#     branches: [ $default-branch ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
     runs-on: ubuntu-latest 
     defaults:
      run:
         working-directory: ./Java_CICD/java_app
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
     
       
     - name: Java jdk setup
       uses: actions/setup-java@v1
       with:
          java-version: 11
      
     - name: maven target # change accordingly
       run: mvn clean install
       
  build-and-push-DockerImage:
    needs: build
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: ./Java_CICD/java_app
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag java-actions-cicd:$(date +%s)
         
